[[redirects]]
  from = "/"
  to = "https://thoughtbot.com/podcasts"
  status = 301
  force = true

[[redirects]]
  from = "/giantrobots.xml"
  to = "https://feeds.simplecast.com/KARThxOK"
  status = 301
  force = true

[[redirects]]
  from = "/buildphase.xml"
  to = "https://feeds.simplecast.com/Negbvh_r"
  status = 301
  force = true

[[redirects]]
  from = "/bikeshed.xml"
  to = "https://feeds.simplecast.com/ky3kewHN"
  status = 301
  force = true

[[redirects]]
  from = "/reboot.xml"
  to = "https://feeds.simplecast.com/SAkbzShV"
  status = 301
  force = true

[[redirects]]
  from = "/:show/:episode"
  to = "https://:show.fm/:episode"
  status = 301
  force = true

[[redirects]]
  from = "/:show"
  to = "https://:show.fm/"
  status = 301
  force = true
